cluster:
  mkdir -p logs/out/{rule} logs/error/{rule} &&
  sbatch
    --partition={resources.partition}
    --account=kernlab
    --cpus-per-task={resources.threads}
    --mem={resources.mem_mb}
    --time={resources.time_min}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/out/{rule}/{rule}-{wildcards}-%j.out
    --error=logs/error/{rule}/{rule}-{wildcards}-%j.err
                --gres=gpu:{resources.gpu}
default-resources:
  - partition=kern
  - time_min=60
  - mem_mb=5000
  - threads=1
  - gpu=0
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 120
jobs: 200
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
